import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

import '../../styles/tokens.dart';

/// `category.icon` keys that currently have a bundled original SVG under
/// `assets/icons/categories_cute/`. Keep this in sync BY HAND
/// whenever an asset is added or removed — `CuteCategoryIcon.maybeBuild`
/// checks membership here before deciding whether to load `<key>.svg` or
/// the generic `_fallback.svg`, so a missing asset never throws at runtime.
///
/// 2026-09-12: expanded from the original 18 to cover every icon key used by
/// a *default* seed category (`SeedService.getDefaultIcon`, 127 distinct
/// values, 2 of which already overlapped the original 18) — 使用者反饋:cute
/// 模式下不該再看到任何 Material 圖示,連沒對應素材的分類也要顯示手繪風,見
/// `_fallbackAssetKey` 那個通用 fallback 圖示。
///
/// 2026-09-12(同日第二次追加):使用者實機看到還有很多自訂/非預設分類的
/// key 仍在顯示 fallback,要求繼續補畫。這次直接补齐
/// `CategoryService.getCategoryIcon`(`category_service.dart` 的 259 條
/// switch)用到的剩余 159 个 key,总共 288 个 + `_fallback` = 289 个素材,
/// 等于整個 icon 對照表全部覆蓋。
const Set<String> kCuteCategoryIconKeys = {
  // 原始 18 個(第一版)
  'restaurant',
  'bakery_dining',
  'directions_bus',
  'shopping_bag',
  'shopping_cart',
  'home',
  'flash_on',
  'sports_esports',
  'local_hospital',
  'menu_book',
  'smartphone',
  'checkroom',
  'card_travel',
  'laptop',
  'pets',
  'fitness_center',
  'account_balance_wallet',
  'trending_up',
  // 2026-09-12 追加:涵盖预设分类用到的其余 111 个 icon key
  'access_time',
  'accessibility',
  'account_balance',
  'apartment',
  'apple',
  'attach_money',
  'attractions',
  'auto_awesome',
  'back_hand',
  'bed',
  'biotech',
  'blender',
  'bubble_chart',
  'build',
  'business_center',
  'cake',
  'candy',
  'card_giftcard',
  'celebration',
  'child_care',
  'chocolate',
  'circle',
  'cleaning_services',
  'cloud',
  'coffee',
  'confirmation_number',
  'construction',
  'content_cut',
  'cookie',
  'delivery_dining',
  'description',
  'devices',
  'diamond',
  'dinner_dining',
  'directions_bike',
  'directions_car',
  'directions_subway',
  'eco',
  'edit',
  'emoji_events',
  'face',
  'face_retouching_natural',
  'family_restroom',
  'fastfood',
  'favorite',
  'flight',
  'free_breakfast',
  'grain',
  'group',
  'handyman',
  'health_and_safety',
  'hiking',
  'home_repair_service',
  'home_work',
  'icecream',
  'juice',
  'kitchen',
  'liquor',
  'local_bar',
  'local_cafe',
  'local_car_wash',
  'local_gas_station',
  'local_laundry_service',
  'local_parking',
  'local_shipping',
  'local_taxi',
  'lunch_dining',
  'medical_services',
  'medication',
  'mic',
  'military_tech',
  'model_training',
  'monetization_on',
  'money_off',
  'movie',
  'music_note',
  'palette',
  'payments',
  'pet_supplies',
  'phone',
  'pie_chart',
  'play_circle',
  'ramen_dining',
  'receipt',
  'receipt_long',
  'report_problem',
  'savings',
  'schedule',
  'school',
  'security',
  'sell',
  'set_meal',
  'show_chart',
  'shower',
  'sports',
  'sports_cricket',
  'sports_martial_arts',
  'star',
  'storefront',
  'subscriptions',
  'trending_down',
  'undo',
  'volunteer_activism',
  'wallet',
  'watch',
  'water_drop',
  'weekend',
  'work',
  'work_outline',
  'workspace_premium',
  'yard',
  // 2026-09-12 第二次追加:补齐 category_service.dart 259 条 switch 里剩余
  // 的 159 个 key,全表覆盖。
  'accessible',
  'add_shopping_cart',
  'agriculture',
  'air',
  'airport_shuttle',
  'alt_route',
  'analytics',
  'auto_stories',
  'autorenew',
  'balance',
  'bathtub',
  'beach_access',
  'boat',
  'book',
  'bookmark',
  'breakfast_dining',
  'brush',
  'bug_report',
  'business',
  'cable',
  'calculate',
  'call_made',
  'call_received',
  'camera_alt',
  'car_rental',
  'casino',
  'category',
  'chair',
  'child_friendly',
  'code',
  'compare_arrows',
  'compass',
  'computer',
  'coronavirus',
  'create',
  'credit_card',
  'cruelty_free',
  'currency_exchange',
  'design_services',
  'desktop_windows',
  'developer_mode',
  'devices_other',
  'directions_railway',
  'directions_transit',
  'directions_walk',
  'dry_cleaning',
  'elderly',
  'electric_bolt',
  'electric_scooter',
  'electrical_services',
  'emoji_nature',
  'energy_savings_leaf',
  'engineering',
  'euro',
  'explore',
  'face_retouching',
  'factory',
  'forest',
  'foundation',
  'games',
  'gavel',
  'gesture',
  'grass',
  'groups',
  'handshake',
  'headphones',
  'headset',
  'healing',
  'hotel',
  'house',
  'hvac',
  'input',
  'inventory',
  'iron',
  'keyboard',
  'label',
  'language',
  'library_books',
  'lightbulb',
  'local_activity',
  'local_dining',
  'local_florist',
  'local_grocery_store',
  'local_mall',
  'local_offer',
  'local_pharmacy',
  'local_pizza',
  'local_post_office',
  'location_on',
  'loyalty',
  'mail',
  'map',
  'medical_information',
  'money',
  'monitor_heart',
  'motorcycle',
  'mouse',
  'move_down',
  'music_video',
  'network_cell',
  'new_releases',
  'nightlife',
  'oil_barrel',
  'paid',
  'park',
  'party_mode',
  'payment',
  'pedal_bike',
  'phone_android',
  'phone_iphone',
  'photo_camera',
  'piano',
  'place',
  'plumbing',
  'pool',
  'price_change',
  'price_check',
  'print',
  'psychology',
  'public',
  'published_with_changes',
  'quiz',
  'real_estate_agent',
  'redeem',
  'refresh',
  'request_quote',
  'restaurant_menu',
  'ring_volume',
  'roofing',
  'router',
  'science',
  'self_improvement',
  'shopping_basket',
  'solar_power',
  'south',
  'spa',
  'sports_basketball',
  'sports_soccer',
  'sports_tennis',
  'store',
  'subway',
  'support_agent',
  'swap_horiz',
  'sync',
  'table_restaurant',
  'tablet',
  'theater_comedy',
  'toll',
  'traffic',
  'train',
  'translate',
  'update',
  'vaccines',
  'verified',
  'videocam',
  'watch_later',
  'wifi',
  'wine_bar',
  'yen',
};

/// Generic hand-drawn placeholder used for any `category.icon` key with no
/// dedicated asset (custom/uncommon categories) — 2026-09-12 使用者反饋:cute
/// 模式下不该再退回 Material 图示,一律显示手绘风(专属的没有就显示这个通用款)。
const String _fallbackAssetKey = '_fallback';

/// Renders the bundled SVG for [iconKey], tinting its `currentColor` line
/// art with [lineColor] (pass `BeeTokens.iconCategory(context)` — the same
/// theme-aware ink token the rest of the app's category icons use). Each
/// icon's own baked accent shape is a literal hex color in the SVG file
/// itself and is unaffected by [lineColor].
///
/// Callers should go through [maybeBuild] rather than constructing this
/// directly.
class CuteCategoryIcon extends StatelessWidget {
  final String iconKey;
  final double size;
  final Color lineColor;

  const CuteCategoryIcon({
    super.key,
    required this.iconKey,
    required this.size,
    required this.lineColor,
  });

  /// Always returns a widget — [iconKey] with a bundled asset renders that
  /// SVG; anything else (unregistered key, or `null`) renders the generic
  /// `_fallback.svg` instead of ever falling back to a Material icon.
  static Widget maybeBuild({
    required String? iconKey,
    required double size,
    required Color lineColor,
  }) {
    final assetKey = (iconKey != null && kCuteCategoryIconKeys.contains(iconKey))
        ? iconKey
        : _fallbackAssetKey;
    return CuteCategoryIcon(iconKey: assetKey, size: size, lineColor: lineColor);
  }

  @override
    Widget build(BuildContext context) {
      // 暗色模式下，線條直接切成白色（或極淺灰）；淺色模式維持原本傳入的 lineColor
      final effectiveLineColor = BeeTokens.isDark(context)
          ? Colors.white.withValues(alpha: 0.9)
          : lineColor;

      return SvgPicture.asset(
        'assets/icons/categories_cute/$iconKey.svg',
        width: size,
        height: size,
        fit: BoxFit.contain,
        theme: SvgTheme(currentColor: effectiveLineColor),
      );
    }
}
